export const Permissions = {
  INTERNAL_NO_PERMISSIONS: "INTERNAL_NO_PERMISSIONS",
  DASHBOARD_READ: "DASHBOARD_READ",
  USERS_READ: "USERS_READ",
  USERS_WRITE: "USERS_WRITE",
  USERS_FORCE_LOGOUT: "USERS_FORCE_LOGOUT",
  NEWS_READ: "NEWS_READ",
  NEWS_WRITE: "NEWS_WRITE",
  NEWS_APPROVE: "NEWS_APPROVE",
  EVENTS_WRITE: "EVENTS_WRITE",
  DOCS_WRITE: "DOCS_WRITE",
  PAGES_WRITE: "PAGES_WRITE",
  BANNERS_WRITE: "BANNERS_WRITE",
  CONFIG_WRITE: "CONFIG_WRITE",
  MEDIA_WRITE: "MEDIA_WRITE",
  VIDEOS_WRITE: "VIDEOS_WRITE",
  CONTACTS_READ: "CONTACTS_READ",
  CONTACTS_WRITE: "CONTACTS_WRITE",
  REPORTS_READ: "REPORTS_READ"
} as const;

export type Permission = (typeof Permissions)[keyof typeof Permissions];
